### PR TITLE
Add a getStep method for clock step "peeking"

### LINKED ISSUE #71: Access to a clock counter
For simulation, it would be convenient to have access to a clock cycle counter. Adding a counter into the design and then routing it to an output is not the best workaround.

### PR DESCRIPTION
**Pull request by carlosedp**
Added a (naive) solution to track the clock steps that is not dependent of the backend.

The solution could track multiple clock domains thru a mutable map of values but the test backend apparently doesn't support it (a test has been written but ignored).

Fixes #71 , #398

### CODE REVIEW

**Comment by carlosedp** [comment]
Would you leave a feedback on this @schoeberl ?

**Comment by schoeberl** [comment]
Nice feature. Maybe we should discuss the name of the function. ```getSteps``` as plural, or better ```getCnt``` as at which count we are.

**Comment by ekiwi** [comment]
> `getSteps` as plural, or better `getCnt` as at which count we are.

I like `getSteps` since the function to advance the clock is called `step`. Another alternative is `getStepCount`.

**Review by ekiwi — COMMENTED** [review]
Thanks for pushing this forward @carlosedp. I might try to change the implementation a bit, but the unit test looks good!

Let's see what name we want to settle on.

**Comment by carlosedp** [comment]
We can discuss on today's dev meeting. Once settled-in, I send an update to the PR.

**Comment by carlosedp** [comment]
Additionally, I'd love to have the multi-clock test case working. Is there anything we can do on some backend for this @ekiwi?

**Comment by ekiwi** [comment]
> Additionally, I'd love to have the multi-clock test case working. Is there anything we can do on some backend for this @ekiwi?

Not without a lot of work. Currently multi clock just isn't supported.

**Review by ekiwi — APPROVED** [review]
LGTM, we just need to decide on whether `getStep` should include the implicit reset cycle or not.

**Comment by carlosedp** [comment]
Thanks for the reimplementation Kevin! I understand that without any `clock.step()` calls, we are at step zero but since the reset is implicit (and happens on first clock) it advances one clock.

I'd vote for user cycles, starting at 0 since the user does not have control over this initial reset.

**Comment by carlosedp** [comment]
I also prefer `getStep` instead of plural `getSteps` as I read it as "We are at step X right now" but it's personal preference :)

**Pull request merged**
