### PR TITLE
remove support for deprecated Interval data type

### PR DESCRIPTION
**Pull request by ekiwi**
Chisel 3.6 deprecated Interval support.

### CODE REVIEW

**Comment by jackkoenig** [comment]
Intervals are deprecated in 3.6, but not removed, I think it would be better for chiseltest to support them for the 3.6.x series. You can suppress the deprecation warnings with `-Wconf` stuff

**Comment by ekiwi** [comment]
> You can suppress the deprecation warnings with `-Wconf` stuff

How exactly would I suppress the Interval warnings while still seeing the Scala 2.13 deprecated warnings?

**Comment by jackkoenig** [comment]
> > You can suppress the deprecation warnings with `-Wconf` stuff
> 
> How exactly would I suppress the Interval warnings while still seeing the Scala 2.13 deprecated warnings?

Here's one way of doing it: https://github.com/ucb-bar/chiseltest/pull/597

**Comment by ekiwi** [comment]
Thanks for showing me how to ignore the warnings @jackkoenig !

**Pull request closed without merging**
