### PR TITLE
Revert version to 6.0-SNAPSHOT and trigger a snapshot release

### PR DESCRIPTION
**Pull request by kammoh**

### CODE REVIEW

**Comment by ekiwi** [comment]
What is your rational for this PR? I am not sure I understand why this is important.

**Comment by kammoh** [comment]
> What is your rational for this PR?
It was just that the non "-SNAPSHOT" artifacts don't seem to be published correctly by the CI. There would be no need if we can have a release soon.

**Comment by ekiwi** [comment]
Oh yeah! Sorry, I somehow thought that this was changing the version of the chisel dependency! Thanks!

**Review by ekiwi — APPROVED** [review]
:shipit:

**Pull request merged**
