### PR TITLE
Support Verilator backend on Windows

### PR DESCRIPTION
**Pull request by howardlau1999**
According to [Spinal HDL documentation](https://spinalhdl.github.io/SpinalDoc-RTD/dev/SpinalHDL/Simulation/install/Verilator.html), Verilator can be used on Windows via MSYS2. But the executable on Windows is `verilator_bin` (see [here](https://github.com/SpinalHDL/SpinalHDL/blob/8631157de28920e6e50854a62f15aaebf52adc62/sim/src/main/scala/spinal/sim/VerilatorBackend.scala#L477)), we need to check the OS to get the correct name.

### CODE REVIEW

**Comment by howardlau1999** [comment]
@jackkoenig PTAL

**Review by ekiwi — CHANGES_REQUESTED** [review]
Thanks! This looks like a good change.

Could you please run `sbt "testOnly -- -n RequiresVerilator"` on your windows machine and confirm that all tests pass?

Then I will be happy to merge.

**Comment by howardlau1999** [comment]
> Thanks! This looks like a good change.
> 
> Could you please run `sbt "testOnly -- -n RequiresVerilator"` on your windows machine and confirm that all tests pass?
> 
> Then I will be happy to merge.

I have added a github action job for windows in the workflow. But it seems the tests were skipped...

**Comment by ekiwi** [comment]
> I have added a github action job for windows in the workflow. But it seems the tests were skipped...

Yeah, not sure what is going on. I would recommend to try and debug on your local Windows machine.

**Comment by howardlau1999** [comment]
> > I have added a github action job for windows in the workflow. But it seems the tests were skipped...
> 
> Yeah, not sure what is going on. I would recommend to try and debug on your local Windows machine.

Some tests failed. I guess that's because their names are too long that leads to error on windows, what should I do?

**Comment by ekiwi** [comment]
> I guess that's because their names are too long that leads to error on windows, what should I do?

Not sure. Sorry, I do not know a lot about Windows.

If your changes improve things for you and since they do not break anything, you could just remove the CI changes and I can merge your changes without tests.

Otherwise you would have to find a way to configure Windows to accept longer filenames.

**Comment by howardlau1999** [comment]
> > I guess that's because their names are too long that leads to error on windows, what should I do?
> 
> Not sure. Sorry, I do not know a lot about Windows.
> 
> If your changes improve things for you and since they do not break anything, you could just remove the CI changes and I can merge your changes without tests.
> 
> Otherwise you would have to find a way to configure Windows to accept longer filenames.

Well, I choose to remove the CI changes and not to fight with windows

**Review by ekiwi — APPROVED** [review]
Thanks!

**Pull request merged**
